# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './rasterProcessor_landscape_widget.ui'
#
# Created: Sun Dec  5 14:47:50 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1056, 545)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1021, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.labelSaveNewRaster = QtGui.QLabel(self.tab)
        self.labelSaveNewRaster.setGeometry(QtCore.QRect(10, 210, 121, 18))
        self.labelSaveNewRaster.setObjectName("labelSaveNewRaster")
        self.btn4 = QtGui.QPushButton(self.tab)
        self.btn4.setGeometry(QtCore.QRect(510, 260, 61, 31))
        self.btn4.setObjectName("btn4")
        self.btnSquared = QtGui.QPushButton(self.tab)
        self.btnSquared.setGeometry(QtCore.QRect(760, 290, 61, 31))
        self.btnSquared.setObjectName("btnSquared")
        self.btnStDev = QtGui.QPushButton(self.tab)
        self.btnStDev.setGeometry(QtCore.QRect(820, 260, 61, 31))
        self.btnStDev.setObjectName("btnStDev")
        self.btn1 = QtGui.QPushButton(self.tab)
        self.btn1.setGeometry(QtCore.QRect(510, 290, 61, 31))
        self.btn1.setObjectName("btn1")
        self.btn9 = QtGui.QPushButton(self.tab)
        self.btn9.setGeometry(QtCore.QRect(630, 230, 61, 31))
        self.btn9.setObjectName("btn9")
        self.btn6 = QtGui.QPushButton(self.tab)
        self.btn6.setGeometry(QtCore.QRect(630, 260, 61, 31))
        self.btn6.setObjectName("btn6")
        self.comboBands = QtGui.QComboBox(self.tab)
        self.comboBands.setGeometry(QtCore.QRect(390, 30, 111, 30))
        self.comboBands.setObjectName("comboBands")
        self.comboBands.addItem("")
        self.btn7 = QtGui.QPushButton(self.tab)
        self.btn7.setGeometry(QtCore.QRect(510, 230, 61, 31))
        self.btn7.setObjectName("btn7")
        self.btnMean = QtGui.QPushButton(self.tab)
        self.btnMean.setGeometry(QtCore.QRect(820, 230, 61, 31))
        self.btnMean.setObjectName("btnMean")
        self.btnRun = QtGui.QPushButton(self.tab)
        self.btnRun.setGeometry(QtCore.QRect(890, 320, 101, 31))
        self.btnRun.setObjectName("btnRun")
        self.btnDivide = QtGui.QPushButton(self.tab)
        self.btnDivide.setGeometry(QtCore.QRect(700, 230, 61, 31))
        self.btnDivide.setObjectName("btnDivide")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(510, 10, 221, 18))
        self.label_2.setObjectName("label_2")
        self.btn8 = QtGui.QPushButton(self.tab)
        self.btn8.setGeometry(QtCore.QRect(570, 230, 61, 31))
        self.btn8.setObjectName("btn8")
        self.btnLBracket = QtGui.QPushButton(self.tab)
        self.btnLBracket.setGeometry(QtCore.QRect(760, 230, 61, 31))
        self.btnLBracket.setObjectName("btnLBracket")
        self.btn3 = QtGui.QPushButton(self.tab)
        self.btn3.setGeometry(QtCore.QRect(630, 290, 61, 31))
        self.btn3.setObjectName("btn3")
        self.comboFormats = QtGui.QComboBox(self.tab)
        self.comboFormats.setGeometry(QtCore.QRect(10, 290, 491, 28))
        self.comboFormats.setObjectName("comboFormats")
        self.comboFormats.addItem("")
        self.comboFormats.addItem("")
        self.lineOutfile = QtGui.QLineEdit(self.tab)
        self.lineOutfile.setGeometry(QtCore.QRect(10, 230, 371, 31))
        self.lineOutfile.setObjectName("lineOutfile")
        self.btn2 = QtGui.QPushButton(self.tab)
        self.btn2.setGeometry(QtCore.QRect(570, 290, 61, 31))
        self.btn2.setObjectName("btn2")
        self.btnPoint = QtGui.QPushButton(self.tab)
        self.btnPoint.setGeometry(QtCore.QRect(570, 320, 61, 31))
        self.btnPoint.setObjectName("btnPoint")
        self.listWidget_Layers = QtGui.QListWidget(self.tab)
        self.listWidget_Layers.setGeometry(QtCore.QRect(10, 30, 371, 131))
        self.listWidget_Layers.setObjectName("listWidget_Layers")
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 18))
        self.label.setObjectName("label")
        self.btnClear = QtGui.QPushButton(self.tab)
        self.btnClear.setGeometry(QtCore.QRect(890, 290, 101, 31))
        self.btnClear.setObjectName("btnClear")
        self.btnSqRoot = QtGui.QPushButton(self.tab)
        self.btnSqRoot.setGeometry(QtCore.QRect(760, 320, 61, 31))
        self.btnSqRoot.setObjectName("btnSqRoot")
        self.btn5 = QtGui.QPushButton(self.tab)
        self.btn5.setGeometry(QtCore.QRect(570, 260, 61, 31))
        self.btn5.setObjectName("btn5")
        self.btnSave = QtGui.QPushButton(self.tab)
        self.btnSave.setEnabled(True)
        self.btnSave.setGeometry(QtCore.QRect(390, 230, 111, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../bin/python/PyQT4/mActionNewVectorLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon)
        self.btnSave.setIconSize(QtCore.QSize(32, 32))
        self.btnSave.setObjectName("btnSave")
        self.checkBoxGenerateOutput = QtGui.QCheckBox(self.tab)
        self.checkBoxGenerateOutput.setGeometry(QtCore.QRect(10, 170, 411, 23))
        self.checkBoxGenerateOutput.setObjectName("checkBoxGenerateOutput")
        self.btnLoad = QtGui.QPushButton(self.tab)
        self.btnLoad.setGeometry(QtCore.QRect(390, 61, 111, 30))
        self.btnLoad.setObjectName("btnLoad")
        self.btn0 = QtGui.QPushButton(self.tab)
        self.btn0.setGeometry(QtCore.QRect(510, 320, 61, 31))
        self.btn0.setObjectName("btn0")
        self.btnAddition = QtGui.QPushButton(self.tab)
        self.btnAddition.setGeometry(QtCore.QRect(700, 320, 61, 31))
        self.btnAddition.setObjectName("btnAddition")
        self.btnRBracket = QtGui.QPushButton(self.tab)
        self.btnRBracket.setGeometry(QtCore.QRect(760, 260, 61, 31))
        self.btnRBracket.setObjectName("btnRBracket")
        self.btnMultiply = QtGui.QPushButton(self.tab)
        self.btnMultiply.setGeometry(QtCore.QRect(700, 260, 61, 31))
        self.btnMultiply.setObjectName("btnMultiply")
        self.btnSubtract = QtGui.QPushButton(self.tab)
        self.btnSubtract.setGeometry(QtCore.QRect(700, 290, 61, 31))
        self.btnSubtract.setObjectName("btnSubtract")
        self.textEqEdit = QtGui.QPlainTextEdit(self.tab)
        self.textEqEdit.setGeometry(QtCore.QRect(510, 30, 481, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEqEdit.sizePolicy().hasHeightForWidth())
        self.textEqEdit.setSizePolicy(sizePolicy)
        self.textEqEdit.setProperty("cursor", QtCore.Qt.IBeamCursor)
        self.textEqEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEqEdit.setObjectName("textEqEdit")
        self.checkBoxQGIS = QtGui.QCheckBox(self.tab)
        self.checkBoxQGIS.setEnabled(True)
        self.checkBoxQGIS.setGeometry(QtCore.QRect(10, 330, 201, 23))
        self.checkBoxQGIS.setChecked(True)
        self.checkBoxQGIS.setTristate(False)
        self.checkBoxQGIS.setObjectName("checkBoxQGIS")
        self.labeloutformat = QtGui.QLabel(self.tab)
        self.labeloutformat.setGeometry(QtCore.QRect(10, 270, 91, 18))
        self.labeloutformat.setObjectName("labeloutformat")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textPyout = QtGui.QTextEdit(self.tab_2)
        self.textPyout.setGeometry(QtCore.QRect(10, 10, 991, 321))
        self.textPyout.setObjectName("textPyout")
        self.btnClearScript = QtGui.QPushButton(self.tab_2)
        self.btnClearScript.setGeometry(QtCore.QRect(790, 340, 101, 31))
        self.btnClearScript.setObjectName("btnClearScript")
        self.btnRunScript = QtGui.QPushButton(self.tab_2)
        self.btnRunScript.setGeometry(QtCore.QRect(900, 340, 101, 31))
        self.btnRunScript.setObjectName("btnRunScript")
        self.btnSaveScript = QtGui.QPushButton(self.tab_2)
        self.btnSaveScript.setGeometry(QtCore.QRect(680, 340, 101, 31))
        self.btnSaveScript.setObjectName("btnSaveScript")
        self.btnOpenScript = QtGui.QPushButton(self.tab_2)
        self.btnOpenScript.setGeometry(QtCore.QRect(570, 340, 101, 31))
        self.btnOpenScript.setObjectName("btnOpenScript")
        self.btnOpenTemplate = QtGui.QPushButton(self.tab_2)
        self.btnOpenTemplate.setGeometry(QtCore.QRect(460, 340, 101, 31))
        self.btnOpenTemplate.setObjectName("btnOpenTemplate")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 17))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 971, 91))
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 971, 61))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 971, 61))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 71, 17))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 101, 17))
        self.label_5.setObjectName("label_5")
        self.btnViewLicense = QtGui.QPushButton(self.tab_3)
        self.btnViewLicense.setGeometry(QtCore.QRect(10, 310, 93, 27))
        self.btnViewLicense.setObjectName("btnViewLicense")
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(120, 310, 331, 21))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_3, "")
        self.labelInformationWindow = QtGui.QLabel(Form)
        self.labelInformationWindow.setGeometry(QtCore.QRect(10, 430, 121, 18))
        self.labelInformationWindow.setObjectName("labelInformationWindow")
        self.textInformation = QtGui.QTextEdit(Form)
        self.textInformation.setGeometry(QtCore.QRect(10, 450, 1021, 81))
        self.textInformation.setObjectName("textInformation")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "PyRaster - Raster Processing Suite [beta 0.9.3] ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSaveNewRaster.setText(QtGui.QApplication.translate("Form", "Save new raster", None, QtGui.QApplication.UnicodeUTF8))
        self.btn4.setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSquared.setToolTip(QtGui.QApplication.translate("Form", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSquared.setText(QtGui.QApplication.translate("Form", "x^2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStDev.setToolTip(QtGui.QApplication.translate("Form", "Global standard deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStDev.setText(QtGui.QApplication.translate("Form", "std", None, QtGui.QApplication.UnicodeUTF8))
        self.btn1.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btn9.setText(QtGui.QApplication.translate("Form", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btn6.setText(QtGui.QApplication.translate("Form", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBands.setToolTip(QtGui.QApplication.translate("Form", "Bands available in selected raster layer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBands.setItemText(0, QtGui.QApplication.translate("Form", "Band #", None, QtGui.QApplication.UnicodeUTF8))
        self.btn7.setText(QtGui.QApplication.translate("Form", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMean.setToolTip(QtGui.QApplication.translate("Form", "Global mean average", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMean.setText(QtGui.QApplication.translate("Form", "mean", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRun.setToolTip(QtGui.QApplication.translate("Form", "Execute calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRun.setText(QtGui.QApplication.translate("Form", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDivide.setToolTip(QtGui.QApplication.translate("Form", "Divide", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDivide.setText(QtGui.QApplication.translate("Form", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Equation Editor: [new raster] =", None, QtGui.QApplication.UnicodeUTF8))
        self.btn8.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLBracket.setToolTip(QtGui.QApplication.translate("Form", "Bracket", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLBracket.setText(QtGui.QApplication.translate("Form", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn3.setText(QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFormats.setToolTip(QtGui.QApplication.translate("Form", "Select output file format", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFormats.setItemText(0, QtGui.QApplication.translate("Form", "GeoTiff (.tif)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFormats.setItemText(1, QtGui.QApplication.translate("Form", "Erdas Imagine (.img)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineOutfile.setToolTip(QtGui.QApplication.translate("Form", "Output raster file", None, QtGui.QApplication.UnicodeUTF8))
        self.btn2.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPoint.setText(QtGui.QApplication.translate("Form", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_Layers.setToolTip(QtGui.QApplication.translate("Form", "Available raster layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Raster Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setToolTip(QtGui.QApplication.translate("Form", "Clear Equation Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setText(QtGui.QApplication.translate("Form", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSqRoot.setToolTip(QtGui.QApplication.translate("Form", "Square Root", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSqRoot.setText(QtGui.QApplication.translate("Form", "sqrt", None, QtGui.QApplication.UnicodeUTF8))
        self.btn5.setText(QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setToolTip(QtGui.QApplication.translate("Form", "Save output file", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("Form", "Open new file", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxGenerateOutput.setText(QtGui.QApplication.translate("Form", "Run without creating new file (output will be shown in log)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setToolTip(QtGui.QApplication.translate("Form", "Load raster band for processing", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("Form", "Load Band", None, QtGui.QApplication.UnicodeUTF8))
        self.btn0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddition.setToolTip(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddition.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRBracket.setToolTip(QtGui.QApplication.translate("Form", "Bracket", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRBracket.setText(QtGui.QApplication.translate("Form", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMultiply.setToolTip(QtGui.QApplication.translate("Form", "Multiply", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMultiply.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSubtract.setToolTip(QtGui.QApplication.translate("Form", "Subtract", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSubtract.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxQGIS.setToolTip(QtGui.QApplication.translate("Form", "Add new raster to QGIS layers", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxQGIS.setText(QtGui.QApplication.translate("Form", "Add new raster to QGIS", None, QtGui.QApplication.UnicodeUTF8))
        self.labeloutformat.setText(QtGui.QApplication.translate("Form", "Output format", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Processor", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearScript.setToolTip(QtGui.QApplication.translate("Form", "Clear Python script", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearScript.setText(QtGui.QApplication.translate("Form", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRunScript.setToolTip(QtGui.QApplication.translate("Form", "Run Python script", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRunScript.setText(QtGui.QApplication.translate("Form", "Run Script", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveScript.setToolTip(QtGui.QApplication.translate("Form", "Save Python script", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveScript.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenScript.setToolTip(QtGui.QApplication.translate("Form", "Open Python script", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenScript.setText(QtGui.QApplication.translate("Form", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenTemplate.setToolTip(QtGui.QApplication.translate("Form", "Open template script", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenTemplate.setText(QtGui.QApplication.translate("Form", "Templates", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Python Script", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Processor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "The Raster Processing Suite is part of the PyRaster project and uses the PyRaster library for processing of raster data. \n"
"Further information can be found at the PyRaster website.\n"
"\n"
"Raster Processing Suite and PyRaster are released under a BSD style license (LICENSE.txt in plugin folder). \n"
"Copyright 2010 Tom Holderness and Newcastle University", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "The raster processor performs numerical operations on raster data. Users must add one or more raster datasets to Qgis before launching. \n"
"Add raster bands to the equation editor by selecting the required band and clicking the \'Load\' button. Output raster images use the projection and \n"
"geo-reference information from the last image loaded into the equation editor.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "The python script shows the python code equivalent to the process in the Processor, this allows users to develop custom scripts for \n"
"automated processing of data. Users can open and save scripts for later use as well as opening template scripts that can be used to develop more \n"
"advanced processes.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Python Script", None, QtGui.QApplication.UnicodeUTF8))
        self.btnViewLicense.setText(QtGui.QApplication.translate("Form", "View license", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"www.students.ncl.ac.uk/tom.holderness/pyraster\"><span style=\" text-decoration: underline; color:#0000ff;\">www.students.ncl.ac.uk/tom.holderness/pyraster</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInformationWindow.setText(QtGui.QApplication.translate("Form", "Information", None, QtGui.QApplication.UnicodeUTF8))

